# MYSQL_VER=8.0 docker compose up --build
version: "2.4"
services:
  db:
    restart: always
    image: datajoint/mysql:${MYSQL_VER}
    environment:
      - MYSQL_ROOT_PASSWORD=${DJ_PASS}
    ports:
      - "3306:3306"
    ## To persist MySQL data and config
    # volumes:
    #   - ./mysql/data:/var/lib/mysql
    #   - ./mysql/my.cnf:/etc/mysql/my.cnf
